source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target "WProficiencyTest" do
        pod "SDWebImage", "~> 4.0"
end


target "WProficiencyTestTests" do
    pod "SDWebImage", "~> 4.0"
end

